### ISSUE TITLE
Licence?

### ISSUE THREAD

**Issue by OverlordZorn** [OverlordZorn/immersion-cigs-rewrite#1]
To complete the paperwork, i'd like to add a licence.
The WW2 Cigs have no Licence
The Immersive Crayons come with some CC 4.0 stuff

@rebelvg
Anything you have in mind?

**Comment by rebelvg** [comment]
for my stuff the license is basically - use anything, just mention me and the team somewhere in the credits, which I know you did 😀
so CC 4.0 I guess.
as for your mod, well, since it's already open-source too I guess you can use the same strategy.

**Comment by OverlordZorn** [comment]
sounds good to me, ill look into the options and throw the same cc 4.0 or a suitable APL in your stuff
